name: macrecovery_x
description: A tool to retrieve a genuine recovery image to recover your Mac.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.4.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 11.1.0
  collection: ^1.17.2
  connectivity_plus: ^7.0.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.0.0
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  pine: ^1.0.2
  provider: ^6.0.5
  rxdart: ^0.28.0
  url_launcher: ^6.2.0

dev_dependencies:
  auto_route_generator:
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  freezed:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/os/lion.jpg
    - assets/os/mountain_lion.webp
    - assets/os/mavericks.jpg
    - assets/os/yosemite.webp
    - assets/os/el_capitan.jpg
    - assets/os/sierra.jpg
    - assets/os/high_sierra.jpg
    - assets/os/mojave.jpg
    - assets/os/catalina.jpg
    - assets/os/big_sur.jpg
    - assets/os/monterey.jpg
    - assets/os/ventura.jpg
    - assets/os/sonoma.jpg
    - assets/os/sequoia.webp
    - assets/os/tahoe.jpg